/* The 59 August reservations, generated from the prototype's
   bookings-august.csv and aligned to the overview's canon: 41 direct
   ($21,380), 29 Autumn-attributed ($15,120 -> $1,965.60 fee at 13%),
   5 with no recorded source, and 7 with a referral recorded outside the
   30-day attribution window. OTA fees: Booking.com 15%, Expedia 18%. */

export type Booking = {
  id: string;
  guest: string;
  city: string;
  channel: "Your website" | "Booking.com" | "Expedia";
  referral: string;
  attributed: boolean;
  /* referral recorded, but outside the 30-day attribution window */
  windowed: boolean;
  booked: string;
  bookedLabel: string;
  arrival: string;
  stayLabel: string;
  nights: number;
  guests: number;
  room: string;
  status: string;
  device: string;
  value: number;
  rate: number;
  fee: number;
  daysAhead: number;
};

export const BOOKINGS: Booking[] = [
  {
    id: "BL-800-1",
    guest: "Margaret P.",
    city: "Boston",
    channel: "Your website",
    referral: "Google Search",
    attributed: false,
    windowed: true,
    booked: "2026-08-03",
    bookedLabel: "Aug 3",
    arrival: "2026-08-10",
    stayLabel: "Aug 10\u201312",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Phone",
    value: 513,
    rate: 0,
    fee: 0,
    daysAhead: 7
  },
  {
    id: "BL-800-2",
    guest: "Daniel R.",
    city: "New York",
    channel: "Your website",
    referral: "Google Maps",
    attributed: true,
    windowed: false,
    booked: "2026-08-04",
    bookedLabel: "Aug 4",
    arrival: "2026-08-18",
    stayLabel: "Aug 18\u201320",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Computer",
    value: 509,
    rate: 0.13,
    fee: 66.17,
    daysAhead: 14
  },
  {
    id: "BL-800-3",
    guest: "Priya K.",
    city: "Hartford",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-05",
    bookedLabel: "Aug 5",
    arrival: "2026-08-26",
    stayLabel: "Aug 26\u201329",
    nights: 3,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 719,
    rate: 0.13,
    fee: 93.47,
    daysAhead: 21
  },
  {
    id: "BL-800-4",
    guest: "Susan L.",
    city: "Burlington",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-06",
    bookedLabel: "Aug 6",
    arrival: "2026-09-03",
    stayLabel: "Sep 3\u20135",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Phone",
    value: 436,
    rate: 0.13,
    fee: 56.68,
    daysAhead: 28
  },
  {
    id: "BL-800-5",
    guest: "Tom W.",
    city: "Boston",
    channel: "Your website",
    referral: "ChatGPT referral",
    attributed: true,
    windowed: false,
    booked: "2026-08-07",
    bookedLabel: "Aug 7",
    arrival: "2026-09-11",
    stayLabel: "Sep 11\u201314",
    nights: 3,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Computer",
    value: 712,
    rate: 0.13,
    fee: 92.56,
    daysAhead: 35
  },
  {
    id: "BL-800-6",
    guest: "Eleanor B.",
    city: "Montreal",
    channel: "Your website",
    referral: "Instagram",
    attributed: false,
    windowed: true,
    booked: "2026-08-08",
    bookedLabel: "Aug 8",
    arrival: "2026-09-19",
    stayLabel: "Sep 19\u201321",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 458,
    rate: 0,
    fee: 0,
    daysAhead: 42
  },
  {
    id: "BL-800-7",
    guest: "Rachel W.",
    city: "New York",
    channel: "Your website",
    referral: "Returning-guest email",
    attributed: true,
    windowed: false,
    booked: "2026-08-03",
    bookedLabel: "Aug 3",
    arrival: "2026-09-21",
    stayLabel: "Sep 21\u201323",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Computer",
    value: 565,
    rate: 0.13,
    fee: 73.45,
    daysAhead: 49
  },
  {
    id: "BL-800-8",
    guest: "James M.",
    city: "Boston",
    channel: "Your website",
    referral: "Not recorded",
    attributed: false,
    windowed: false,
    booked: "2026-08-04",
    bookedLabel: "Aug 4",
    arrival: "2026-09-29",
    stayLabel: "Sep 29 \u2013 Oct 1",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Phone",
    value: 359,
    rate: 0,
    fee: 0,
    daysAhead: 56
  },
  {
    id: "BL-800-9",
    guest: "Helen C.",
    city: "Boston",
    channel: "Your website",
    referral: "Google Maps",
    attributed: true,
    windowed: false,
    booked: "2026-08-05",
    bookedLabel: "Aug 5",
    arrival: "2026-08-16",
    stayLabel: "Aug 16\u201318",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 432,
    rate: 0.13,
    fee: 56.16,
    daysAhead: 11
  },
  {
    id: "BL-800-10",
    guest: "David A.",
    city: "Albany",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-06",
    bookedLabel: "Aug 6",
    arrival: "2026-08-24",
    stayLabel: "Aug 24\u201326",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Computer",
    value: 513,
    rate: 0.13,
    fee: 66.69,
    daysAhead: 18
  },
  {
    id: "BL-800-11",
    guest: "Olivia T.",
    city: "New York",
    channel: "Your website",
    referral: "Google Maps",
    attributed: true,
    windowed: false,
    booked: "2026-08-07",
    bookedLabel: "Aug 7",
    arrival: "2026-09-01",
    stayLabel: "Sep 1\u20133",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Tablet",
    value: 560,
    rate: 0.13,
    fee: 72.8,
    daysAhead: 25
  },
  {
    id: "BL-800-12",
    guest: "Michael S.",
    city: "Hartford",
    channel: "Your website",
    referral: "Google Search",
    attributed: false,
    windowed: true,
    booked: "2026-08-10",
    bookedLabel: "Aug 10",
    arrival: "2026-09-11",
    stayLabel: "Sep 11\u201314",
    nights: 3,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 719,
    rate: 0,
    fee: 0,
    daysAhead: 32
  },
  {
    id: "BL-800-13",
    guest: "Claire N.",
    city: "Burlington",
    channel: "Your website",
    referral: "ChatGPT referral",
    attributed: true,
    windowed: false,
    booked: "2026-08-11",
    bookedLabel: "Aug 11",
    arrival: "2026-09-19",
    stayLabel: "Sep 19\u201321",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Phone",
    value: 436,
    rate: 0.13,
    fee: 56.68,
    daysAhead: 39
  },
  {
    id: "BL-800-14",
    guest: "Ben H.",
    city: "Boston",
    channel: "Your website",
    referral: "Instagram",
    attributed: false,
    windowed: true,
    booked: "2026-08-12",
    bookedLabel: "Aug 12",
    arrival: "2026-09-27",
    stayLabel: "Sep 27\u201329",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Computer",
    value: 356,
    rate: 0,
    fee: 0,
    daysAhead: 46
  },
  {
    id: "BL-800-15",
    guest: "Nora J.",
    city: "Montreal",
    channel: "Your website",
    referral: "Returning-guest email",
    attributed: true,
    windowed: false,
    booked: "2026-08-13",
    bookedLabel: "Aug 13",
    arrival: "2026-09-30",
    stayLabel: "Sep 30 \u2013 Oct 2",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 565,
    rate: 0.13,
    fee: 73.45,
    daysAhead: 48
  },
  {
    id: "BL-800-16",
    guest: "Louis F.",
    city: "New York",
    channel: "Your website",
    referral: "Not recorded",
    attributed: false,
    windowed: false,
    booked: "2026-08-14",
    bookedLabel: "Aug 14",
    arrival: "2026-08-22",
    stayLabel: "Aug 22\u201325",
    nights: 3,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Phone",
    value: 640,
    rate: 0,
    fee: 0,
    daysAhead: 8
  },
  {
    id: "BL-800-17",
    guest: "Amelia D.",
    city: "Boston",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-15",
    bookedLabel: "Aug 15",
    arrival: "2026-08-30",
    stayLabel: "Aug 30 \u2013 Sep 1",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Computer",
    value: 359,
    rate: 0.13,
    fee: 46.67,
    daysAhead: 15
  },
  {
    id: "BL-800-18",
    guest: "Robert V.",
    city: "Boston",
    channel: "Your website",
    referral: "Google Maps",
    attributed: true,
    windowed: false,
    booked: "2026-08-10",
    bookedLabel: "Aug 10",
    arrival: "2026-09-01",
    stayLabel: "Sep 1\u20133",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 509,
    rate: 0.13,
    fee: 66.17,
    daysAhead: 22
  },
  {
    id: "BL-800-19",
    guest: "Sophie G.",
    city: "New York",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-11",
    bookedLabel: "Aug 11",
    arrival: "2026-09-09",
    stayLabel: "Sep 9\u201311",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Phone",
    value: 513,
    rate: 0.13,
    fee: 66.69,
    daysAhead: 29
  },
  {
    id: "BL-800-20",
    guest: "Peter E.",
    city: "Hartford",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-12",
    bookedLabel: "Aug 12",
    arrival: "2026-09-17",
    stayLabel: "Sep 17\u201320",
    nights: 3,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Computer",
    value: 719,
    rate: 0.13,
    fee: 93.47,
    daysAhead: 36
  },
  {
    id: "BL-800-21",
    guest: "Emma R.",
    city: "Burlington",
    channel: "Your website",
    referral: "ChatGPT referral",
    attributed: false,
    windowed: true,
    booked: "2026-08-13",
    bookedLabel: "Aug 13",
    arrival: "2026-09-25",
    stayLabel: "Sep 25\u201328",
    nights: 3,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 712,
    rate: 0,
    fee: 0,
    daysAhead: 43
  },
  {
    id: "BL-800-22",
    guest: "Alex K.",
    city: "Portland",
    channel: "Your website",
    referral: "Instagram",
    attributed: true,
    windowed: false,
    booked: "2026-08-17",
    bookedLabel: "Aug 17",
    arrival: "2026-09-30",
    stayLabel: "Sep 30 \u2013 Oct 2",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Computer",
    value: 436,
    rate: 0.13,
    fee: 56.68,
    daysAhead: 44
  },
  {
    id: "BL-800-23",
    guest: "Grace M.",
    city: "Providence",
    channel: "Your website",
    referral: "Returning-guest email",
    attributed: true,
    windowed: false,
    booked: "2026-08-18",
    bookedLabel: "Aug 18",
    arrival: "2026-09-30",
    stayLabel: "Sep 30 \u2013 Oct 2",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Phone",
    value: 565,
    rate: 0.13,
    fee: 73.45,
    daysAhead: 43
  },
  {
    id: "BL-800-24",
    guest: "Adam L.",
    city: "Boston",
    channel: "Your website",
    referral: "Not recorded",
    attributed: false,
    windowed: false,
    booked: "2026-08-19",
    bookedLabel: "Aug 19",
    arrival: "2026-08-31",
    stayLabel: "Aug 31 \u2013 Sep 2",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 432,
    rate: 0,
    fee: 0,
    daysAhead: 12
  },
  {
    id: "BL-800-25",
    guest: "Julia C.",
    city: "Boston",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-20",
    bookedLabel: "Aug 20",
    arrival: "2026-09-08",
    stayLabel: "Sep 8\u201310",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Computer",
    value: 359,
    rate: 0.13,
    fee: 46.67,
    daysAhead: 19
  },
  {
    id: "BL-800-26",
    guest: "Oliver B.",
    city: "New York",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-21",
    bookedLabel: "Aug 21",
    arrival: "2026-09-16",
    stayLabel: "Sep 16\u201318",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Phone",
    value: 389,
    rate: 0.13,
    fee: 50.57,
    daysAhead: 26
  },
  {
    id: "BL-800-27",
    guest: "Hannah P.",
    city: "Montreal",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-22",
    bookedLabel: "Aug 22",
    arrival: "2026-09-24",
    stayLabel: "Sep 24\u201326",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 513,
    rate: 0.13,
    fee: 66.69,
    daysAhead: 33
  },
  {
    id: "BL-800-28",
    guest: "William D.",
    city: "Boston",
    channel: "Your website",
    referral: "Google Maps",
    attributed: true,
    windowed: false,
    booked: "2026-08-17",
    bookedLabel: "Aug 17",
    arrival: "2026-09-26",
    stayLabel: "Sep 26\u201328",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Computer",
    value: 559,
    rate: 0.13,
    fee: 72.67,
    daysAhead: 40
  },
  {
    id: "BL-800-29",
    guest: "Isabel S.",
    city: "Hartford",
    channel: "Your website",
    referral: "ChatGPT referral",
    attributed: true,
    windowed: false,
    booked: "2026-08-18",
    bookedLabel: "Aug 18",
    arrival: "2026-09-30",
    stayLabel: "Sep 30 \u2013 Oct 3",
    nights: 3,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Phone",
    value: 719,
    rate: 0.13,
    fee: 93.47,
    daysAhead: 43
  },
  {
    id: "BL-800-30",
    guest: "Nathan T.",
    city: "Burlington",
    channel: "Your website",
    referral: "Instagram",
    attributed: true,
    windowed: false,
    booked: "2026-08-19",
    bookedLabel: "Aug 19",
    arrival: "2026-09-30",
    stayLabel: "Sep 30 \u2013 Oct 2",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 436,
    rate: 0.13,
    fee: 56.68,
    daysAhead: 42
  },
  {
    id: "BL-800-31",
    guest: "Elena F.",
    city: "New York",
    channel: "Your website",
    referral: "Returning-guest email",
    attributed: false,
    windowed: true,
    booked: "2026-08-24",
    bookedLabel: "Aug 24",
    arrival: "2026-09-02",
    stayLabel: "Sep 2\u20134",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Computer",
    value: 356,
    rate: 0,
    fee: 0,
    daysAhead: 9
  },
  {
    id: "BL-800-32",
    guest: "Theo W.",
    city: "Boston",
    channel: "Your website",
    referral: "Not recorded",
    attributed: false,
    windowed: false,
    booked: "2026-08-25",
    bookedLabel: "Aug 25",
    arrival: "2026-09-10",
    stayLabel: "Sep 10\u201312",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Tablet",
    value: 565,
    rate: 0,
    fee: 0,
    daysAhead: 16
  },
  {
    id: "BL-800-33",
    guest: "Alice J.",
    city: "Albany",
    channel: "Your website",
    referral: "Google Maps",
    attributed: true,
    windowed: false,
    booked: "2026-08-26",
    bookedLabel: "Aug 26",
    arrival: "2026-10-03",
    stayLabel: "Oct 3\u20135",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 509,
    rate: 0.13,
    fee: 66.17,
    daysAhead: 38
  },
  {
    id: "BL-800-34",
    guest: "Samuel N.",
    city: "Boston",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-27",
    bookedLabel: "Aug 27",
    arrival: "2026-10-06",
    stayLabel: "Oct 6\u20138",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Phone",
    value: 359,
    rate: 0.13,
    fee: 46.67,
    daysAhead: 40
  },
  {
    id: "BL-800-35",
    guest: "Lucy V.",
    city: "New York",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-28",
    bookedLabel: "Aug 28",
    arrival: "2026-10-09",
    stayLabel: "Oct 9\u201311",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Computer",
    value: 513,
    rate: 0.13,
    fee: 66.69,
    daysAhead: 42
  },
  {
    id: "BL-800-36",
    guest: "Henry A.",
    city: "Montreal",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-29",
    bookedLabel: "Aug 29",
    arrival: "2026-10-12",
    stayLabel: "Oct 12\u201314",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 503,
    rate: 0.13,
    fee: 65.39,
    daysAhead: 44
  },
  {
    id: "BL-800-37",
    guest: "Maya H.",
    city: "Boston",
    channel: "Your website",
    referral: "ChatGPT referral",
    attributed: true,
    windowed: false,
    booked: "2026-08-24",
    bookedLabel: "Aug 24",
    arrival: "2026-10-15",
    stayLabel: "Oct 15\u201318",
    nights: 3,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Computer",
    value: 712,
    rate: 0.13,
    fee: 92.56,
    daysAhead: 52
  },
  {
    id: "BL-800-38",
    guest: "Thomas G.",
    city: "Hartford",
    channel: "Your website",
    referral: "Instagram",
    attributed: false,
    windowed: true,
    booked: "2026-08-25",
    bookedLabel: "Aug 25",
    arrival: "2026-10-18",
    stayLabel: "Oct 18\u201321",
    nights: 3,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Phone",
    value: 718,
    rate: 0,
    fee: 0,
    daysAhead: 54
  },
  {
    id: "BL-800-39",
    guest: "Eva E.",
    city: "Burlington",
    channel: "Your website",
    referral: "Returning-guest email",
    attributed: true,
    windowed: false,
    booked: "2026-08-26",
    bookedLabel: "Aug 26",
    arrival: "2026-10-21",
    stayLabel: "Oct 21\u201323",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Phone",
    value: 436,
    rate: 0.13,
    fee: 56.68,
    daysAhead: 56
  },
  {
    id: "BL-800-40",
    guest: "Leo C.",
    city: "New York",
    channel: "Your website",
    referral: "Not recorded",
    attributed: false,
    windowed: false,
    booked: "2026-08-27",
    bookedLabel: "Aug 27",
    arrival: "2026-10-24",
    stayLabel: "Oct 24\u201326",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Computer",
    value: 432,
    rate: 0,
    fee: 0,
    daysAhead: 58
  },
  {
    id: "BL-800-41",
    guest: "Diana R.",
    city: "Boston",
    channel: "Your website",
    referral: "Google Search",
    attributed: true,
    windowed: false,
    booked: "2026-08-28",
    bookedLabel: "Aug 28",
    arrival: "2026-10-27",
    stayLabel: "Oct 27\u201329",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Phone",
    value: 565,
    rate: 0.13,
    fee: 73.45,
    daysAhead: 60
  },
  {
    id: "OTA-8-1",
    guest: "Jamie S.",
    city: "Boston",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-01",
    bookedLabel: "Aug 1",
    arrival: "2026-08-13",
    stayLabel: "Aug 13\u201315",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 428,
    rate: 0.15,
    fee: 64.2,
    daysAhead: 12
  },
  {
    id: "OTA-8-2",
    guest: "Morgan L.",
    city: "New York",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-03",
    bookedLabel: "Aug 3",
    arrival: "2026-08-18",
    stayLabel: "Aug 18\u201321",
    nights: 3,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Not recorded",
    value: 642,
    rate: 0.15,
    fee: 96.3,
    daysAhead: 15
  },
  {
    id: "OTA-8-3",
    guest: "Taylor D.",
    city: "Hartford",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-05",
    bookedLabel: "Aug 5",
    arrival: "2026-08-23",
    stayLabel: "Aug 23\u201325",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 428,
    rate: 0.15,
    fee: 64.2,
    daysAhead: 18
  },
  {
    id: "OTA-8-4",
    guest: "Casey A.",
    city: "Burlington",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-07",
    bookedLabel: "Aug 7",
    arrival: "2026-08-28",
    stayLabel: "Aug 28\u201331",
    nights: 3,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 642,
    rate: 0.15,
    fee: 96.3,
    daysAhead: 21
  },
  {
    id: "OTA-8-5",
    guest: "Robin F.",
    city: "Boston",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-08",
    bookedLabel: "Aug 8",
    arrival: "2026-09-01",
    stayLabel: "Sep 1\u20133",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Not recorded",
    value: 428,
    rate: 0.15,
    fee: 64.2,
    daysAhead: 24
  },
  {
    id: "OTA-8-6",
    guest: "Avery W.",
    city: "Montreal",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-10",
    bookedLabel: "Aug 10",
    arrival: "2026-09-06",
    stayLabel: "Sep 6\u20139",
    nights: 3,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 642,
    rate: 0.15,
    fee: 96.3,
    daysAhead: 27
  },
  {
    id: "OTA-8-7",
    guest: "Cameron B.",
    city: "New York",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-12",
    bookedLabel: "Aug 12",
    arrival: "2026-09-11",
    stayLabel: "Sep 11\u201313",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 428,
    rate: 0.15,
    fee: 64.2,
    daysAhead: 30
  },
  {
    id: "OTA-8-8",
    guest: "Jordan K.",
    city: "Boston",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-13",
    bookedLabel: "Aug 13",
    arrival: "2026-09-15",
    stayLabel: "Sep 15\u201318",
    nights: 3,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Not recorded",
    value: 642,
    rate: 0.15,
    fee: 96.3,
    daysAhead: 33
  },
  {
    id: "OTA-8-9",
    guest: "Jamie S.",
    city: "Boston",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-15",
    bookedLabel: "Aug 15",
    arrival: "2026-09-20",
    stayLabel: "Sep 20\u201322",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 428,
    rate: 0.15,
    fee: 64.2,
    daysAhead: 36
  },
  {
    id: "OTA-8-10",
    guest: "Morgan L.",
    city: "Albany",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-17",
    bookedLabel: "Aug 17",
    arrival: "2026-09-25",
    stayLabel: "Sep 25\u201328",
    nights: 3,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 642,
    rate: 0.15,
    fee: 96.3,
    daysAhead: 39
  },
  {
    id: "OTA-8-11",
    guest: "Taylor D.",
    city: "New York",
    channel: "Booking.com",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-19",
    bookedLabel: "Aug 19",
    arrival: "2026-09-30",
    stayLabel: "Sep 30 \u2013 Oct 2",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Not recorded",
    value: 428,
    rate: 0.15,
    fee: 64.2,
    daysAhead: 42
  },
  {
    id: "OTA-8-12",
    guest: "Casey A.",
    city: "Hartford",
    channel: "Expedia",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-20",
    bookedLabel: "Aug 20",
    arrival: "2026-10-04",
    stayLabel: "Oct 4\u20137",
    nights: 3,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 672,
    rate: 0.18,
    fee: 120.96,
    daysAhead: 45
  },
  {
    id: "OTA-8-13",
    guest: "Robin F.",
    city: "Burlington",
    channel: "Expedia",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-22",
    bookedLabel: "Aug 22",
    arrival: "2026-10-09",
    stayLabel: "Oct 9\u201311",
    nights: 2,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 448,
    rate: 0.18,
    fee: 80.64,
    daysAhead: 48
  },
  {
    id: "OTA-8-14",
    guest: "Avery W.",
    city: "Boston",
    channel: "Expedia",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-24",
    bookedLabel: "Aug 24",
    arrival: "2026-10-14",
    stayLabel: "Oct 14\u201317",
    nights: 3,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Not recorded",
    value: 672,
    rate: 0.18,
    fee: 120.96,
    daysAhead: 51
  },
  {
    id: "OTA-8-15",
    guest: "Cameron B.",
    city: "Montreal",
    channel: "Expedia",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-25",
    bookedLabel: "Aug 25",
    arrival: "2026-09-06",
    stayLabel: "Sep 6\u20138",
    nights: 2,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 448,
    rate: 0.18,
    fee: 80.64,
    daysAhead: 12
  },
  {
    id: "OTA-8-16",
    guest: "Jordan K.",
    city: "New York",
    channel: "Expedia",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-27",
    bookedLabel: "Aug 27",
    arrival: "2026-09-11",
    stayLabel: "Sep 11\u201314",
    nights: 3,
    guests: 2,
    room: "Garden Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 672,
    rate: 0.18,
    fee: 120.96,
    daysAhead: 15
  },
  {
    id: "OTA-8-17",
    guest: "Jamie S.",
    city: "Boston",
    channel: "Expedia",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-29",
    bookedLabel: "Aug 29",
    arrival: "2026-09-16",
    stayLabel: "Sep 16\u201318",
    nights: 2,
    guests: 2,
    room: "Lantern Suite",
    status: "Confirmed",
    device: "Not recorded",
    value: 448,
    rate: 0.18,
    fee: 80.64,
    daysAhead: 18
  },
  {
    id: "OTA-8-18",
    guest: "Morgan L.",
    city: "Boston",
    channel: "Expedia",
    referral: "Booking-site referral unavailable",
    attributed: false,
    windowed: false,
    booked: "2026-08-31",
    bookedLabel: "Aug 31",
    arrival: "2026-09-21",
    stayLabel: "Sep 21\u201324",
    nights: 3,
    guests: 2,
    room: "Meadow Room",
    status: "Confirmed",
    device: "Not recorded",
    value: 672,
    rate: 0.18,
    fee: 120.96,
    daysAhead: 21
  }
];
